export const EstadoPedido = Object.freeze({
  PENDIENTE: 'PENDIENTE',
  CONFIRMADO: 'CONFIRMADO',
  EN_REVISION: 'EN_REVISION',
  PENDIENTE_CAMBIOS: 'PENDIENTE_CAMBIOS',
  ENTREGADO: 'ENTREGADO',
  CANCELADO: 'CANCELADO'
});
